import type { Game } from '@/lib/types';

/**
 * Read from the nine design documents in C:/Unity/Temp — the intro script, six
 * chapter documents, the gameplay category library and the Production Master
 * Plan v1 (20 September 2026). The percentages come from that plan's own
 * position: the documents are a foundation, not a technical specification, and
 * the only code that exists is grey-box prototype scenes.
 *
 * The title is genuinely undecided — the overview document says so on line one.
 * The two leads carry the working names from those documents.
 *
 * Images: environment renders from C:/Unity/Temp/Environment_V1, storyboard
 * frames from C:/Unity/Temp/StoryBoard paired with the Environment_V1 remake of
 * the same shot, and cast cards rendered from the Tripo FBX files with
 * tools/render-character.py. All re-encoded to WebP under public/works/untitled-co-op.
 */
export const untitledCoop: Game = {
  slug: 'untitled-co-op',
  title: 'Untitled',
  subtitle: 'The two-player project',
  logline:
    'A two-player story adventure. Two ordinary teenagers, one kingdom failing from both directions, and two completely different ways of trying to save it.',
  hook: 'A puppet master asks a crowd who will save them. Two people in that crowd are the answer — and neither of them gets there without the other player.',

  status: 'design',
  statusNote: 'Storyboarded, blocked out and cast. Nothing playable yet.',

  tracks: [
    { name: 'Story, chapter design and storyboards', pct: 35, weight: 1 },
    { name: 'Environment blockouts — seven locations', pct: 35, weight: 1 },
    { name: 'Characters and animation', pct: 20, weight: 1 },
    { name: 'Grey-box prototype scenes', pct: 6, weight: 1 },
    { name: 'Playable acts — five chapters', pct: 0, weight: 5 },
    { name: 'Co-op, split-screen, checkpoints', pct: 0, weight: 5 },
    { name: 'Combat, traversal, interaction systems', pct: 0, weight: 4 },
    { name: 'Cinematics and audio', pct: 5, weight: 1 },
  ],
  progressNote:
    'Weighted against what gates a playable build, not against how much art exists. The intro and Chapters 1–5 are storyboarded, every location is blocked out in Blender, and the main cast is modelled — but none of it is in Unity yet, and the three grey-box prototype scenes are the only code. Nothing counts as a completed act until it has an objective, escalation, failure, recovery and tested entry and exit — by that definition none of them are done.',

  started: 'September 2026',
  engine: 'Unity 6 · proposed',
  genre: 'Co-op story adventure',
  format: 'Two-player · split-screen and online',
  platforms: ['PC target'],

  role: [
    'Concept and story — the cinematic intro script, six chapter documents, and the agreed creative boundaries the production plan is not allowed to quietly widen',
    'Production planning — eleven phases with gate criteria, a scope model, per-chapter work packages and acceptance tests, written before any of it is built',
    'Grey-box prototypes in Unity 6 — shop, festival and two-fronts scenes, built headless and smoke-checked',
    'Storyboards — about 120 split-screen frames from the intro to the Chapter 5 reunion, each one then rebuilt as a camera in the Blender scenes',
    'Environment blockouts in Blender — seven locations generated by Python build scripts, with a named camera on every gameplay stop and a top-down route map per chapter',
    'Casting and art direction — character reference sheets for the leads, their families, the court and the army, and the models built from them',
  ],
  disclosure:
    'Planned as a solo production using AI throughout, with human direction, playtesting and occasional bought-in specialists. The storyboard frames are AI-generated concept images, the character models are Tripo generations, and the animation library is Mixamo. Generated content does not count as gameplay until it works in the build.',

  showStanding: true,
  standingAt: 'end',
  accent: '#C98A3C',
  cover: '/works/untitled-co-op/leads.webp',
  hero: { src: '/works/untitled-co-op/leads.webp', fit: 'contain', position: '84% 72%' },
  showcase: {
    src: '/works/untitled-co-op/places/01-puppet-square-aerial.webp',
    note: 'Puppet Square at night · Blender blockout',
    fit: 'cover',
  },

  links: [],
  metrics: [
    { k: 'Chapters', v: '5', sub: 'playable, plus an epilogue' },
    { k: 'Players', v: '2', sub: 'no solo mode planned' },
    { k: 'Locations', v: '7', sub: 'blocked out in Blender' },
    { k: 'Storyboard', v: '~120', sub: 'frames, intro to Chapter 5' },
    { k: 'Team', v: '1' },
  ],

  blocks: [
    {
      kind: 'story',
      id: 'story',
      label: 'The story',
      heading: 'The whole game in thirteen frames',
      intro:
        'Read top to bottom. The painted frames are AI-generated storyboards: they show what each moment is meant to be, not what the game looks like. The inset in the corner is the same shot as it is actually built in Blender — click it to swap them.',
      items: [
        {
          chapter: 'Opening · The Puppet Show',
          title: 'A kingdom losing on two fronts',
          caption: 'Outside the walls, the army is starving and outnumbered. Inside the palace, officials sit on the grain they took and read a surrender offer.',
          board: '/works/untitled-co-op/story/01-board.webp',
          boardLabel: 'Storyboard · AI concept',
          sides: ['Outside · the war', 'Inside · the palace'],
        },
        {
          chapter: 'Opening · The Puppet Show',
          title: 'It was a puppet show',
          caption: 'Both scenes turn to painted wood on a stage in front of a crowd. The puppet master asks them who will save the country — and the light stays on two teenagers in the audience.',
          board: '/works/untitled-co-op/story/02-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/02-blockout.webp',
          builtLabel: 'Blender blockout',
        },
        {
          chapter: 'Chapter 1 · Two Worlds',
          title: 'Two lives, one screen',
          caption: 'The screen splits and both players start at once, as strangers. Tấm stocks a provisions shop; Cám clears fallen timber. Each is working their way home to their mother.',
          board: '/works/untitled-co-op/story/03-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/03-blockout.webp',
          builtLabel: 'Blender blockout',
          sides: ['Player 1 · Tấm', 'Player 2 · Cám'],
        },
        {
          chapter: 'Chapter 2 · The Festival',
          title: 'They meet',
          caption: 'A gang corners Tấm at the festival. Cám steps in — and now they are both outnumbered and have to run.',
          board: '/works/untitled-co-op/story/04-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/04-blockout.webp',
          builtLabel: 'Blender blockout',
          sides: ['Player 1 · Tấm', 'Player 2 · Cám'],
        },
        {
          chapter: 'Chapter 2 · The Festival',
          title: 'One costume, two players',
          caption: 'The escape only works together. Hidden inside a dragon costume, each player carries one end, and they have to move in step to get through the crowd.',
          board: '/works/untitled-co-op/story/05-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/05-blockout.webp',
          builtLabel: 'Blender blockout',
          sides: ['Player 1 · Tấm', 'Player 2 · Cám'],
        },
        {
          chapter: 'Chapter 2 · The Festival',
          title: 'Out by boat',
          caption: 'The last stretch is one boat and two paddles, rowed in rhythm away from the festival. They part with a kiss on the cheek.',
          board: '/works/untitled-co-op/story/06-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/06-blockout.webp',
          builtLabel: 'Blender blockout',
          sides: ['Player 1 · Tấm', 'Player 2 · Cám'],
        },
        {
          chapter: 'Chapter 3 · The Drink Shop',
          title: 'Working side by side',
          caption: 'Their mothers end up at the same restaurant, and the two of them are put in charge of the drink shop next door. The war reaches them through the customers first — a wounded soldier on day two.',
          board: '/works/untitled-co-op/story/07-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/07-blockout.webp',
          builtLabel: 'Blender blockout',
        },
        {
          chapter: 'Chapter 3 · The Drink Shop',
          title: 'Officers who never pay',
          caption: 'On day three the officers are served first and walk out without paying. The two of them count what the day cost.',
          board: '/works/untitled-co-op/story/08-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/08-blockout.webp',
          builtLabel: 'Blender blockout',
        },
        {
          chapter: 'Chapter 3 · The Drink Shop',
          title: 'The invasion reaches them',
          caption: 'On day five the news comes, civilians pour in, and the shop closes early. Everyone leaves for the capital.',
          board: '/works/untitled-co-op/story/09-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/09-blockout.webp',
          builtLabel: 'Blender blockout',
        },
        {
          chapter: 'Chapter 4 · The Recruitment',
          title: 'The king promises protection',
          caption: 'They enter the palace courtyard together, among thousands of displaced people, and hear the king speak.',
          board: '/works/untitled-co-op/story/10-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/10-blockout.webp',
          builtLabel: 'Blender blockout',
        },
        {
          chapter: 'Chapter 4 · The Recruitment',
          title: 'Two paths',
          caption: 'Afterwards they split up. Tấm stays with the refugees, learning what help they need and why it never arrived. Cám enlists and trains.',
          board: '/works/untitled-co-op/story/11-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/11-blockout.webp',
          builtLabel: 'Blender blockout',
          sides: ['Player 1 · Tấm', 'Player 2 · Cám'],
        },
        {
          chapter: 'Chapter 5 · Two Fronts',
          title: 'Inside the palace, and at the front',
          caption: 'Two different games at once. Tấm works her way into the palace and uncovers the surrender — she never fights. Cám fights beside his crew until he is ordered to abandon the people, and refuses.',
          board: '/works/untitled-co-op/story/12-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/12-blockout.webp',
          builtLabel: 'Blender blockout',
          sides: ['Player 1 · Tấm', 'Player 2 · Cám'],
        },
        {
          chapter: 'Chapter 5 · Two Fronts',
          title: 'Reunion',
          caption: 'She brings out the people the palace left behind; he brings his crew. The playable story ends here, with a plan to take the palace back. A cinematic epilogue follows — not boarded yet.',
          board: '/works/untitled-co-op/story/13-board.webp',
          boardLabel: 'Storyboard · AI concept',
          built: '/works/untitled-co-op/story/13-blockout.webp',
          builtLabel: 'Blender blockout',
        },
      ],
    },
    {
      kind: 'cast',
      id: 'cast',
      label: 'Cast',
      heading: 'Two players, two families, and the people above them',
      intro:
        'Working names from the design documents. Both leads appear twice — as teenagers for the first four chapters and grown for the last. Press 3D on a card to turn the model.',
      items: [
        {
          slug: 'tam-young',
          name: 'Tấm',
          role: 'Player one · Chapters 1–4',
          note: 'Starts in a provisions shop and a restaurant kitchen, and learns what is wrong with the kingdom from the people she serves.',
          model: '/works/untitled-co-op/cast/tam-young.glb',
          image: '/works/untitled-co-op/cast/tam-young.webp',
        },
        {
          slug: 'cam-young',
          name: 'Cám',
          role: 'Player two · Chapters 1–4',
          note: 'Starts logging, on the river and on the hillside. Steps in when she is cornered at the festival, and they are immediately outnumbered.',
          model: '/works/untitled-co-op/cast/cam-young.glb',
          image: '/works/untitled-co-op/cast/cam-young.webp',
        },
        {
          slug: 'tam-adult',
          name: 'Tấm',
          role: 'Player one · Chapter 5',
          note: 'Goes in through the palace service gate with a kitchen job. Never fights. Gets the abandoned people out and loses her place for it.',
          model: '/works/untitled-co-op/cast/tam-adult.glb',
          image: '/works/untitled-co-op/cast/tam-adult.webp',
        },
        {
          slug: 'cam-adult',
          name: 'Cám',
          role: 'Player two · Chapter 5',
          note: 'Goes to the front with his crew. In the final battle he refuses an order that would abandon the people, and wins anyway.',
          model: '/works/untitled-co-op/cast/cam-adult.glb',
          image: '/works/untitled-co-op/cast/cam-adult.webp',
        },
        {
          slug: 'tam-mother',
          name: 'Tấm’s mother',
          role: 'Family',
          note: 'Where Tấm’s route ends in Chapter 1. By the drink shop chapter she and Cám’s mother are working side by side.',
          model: '/works/untitled-co-op/cast/tam-mother.glb',
          image: '/works/untitled-co-op/cast/tam-mother.webp',
        },
        {
          slug: 'cam-mother',
          name: 'Cám’s mother',
          role: 'Family',
          note: 'Takes a job at the restaurant where Tấm works — which is how the two of them end up running the drink shop next door.',
          model: '/works/untitled-co-op/cast/cam-mother.glb',
          image: '/works/untitled-co-op/cast/cam-mother.webp',
        },
        {
          slug: 'king',
          name: 'The King',
          role: 'The palace',
          note: 'Promises the people protection in Chapter 4. What the palace does with that promise is what Tấm finds out in Chapter 5.',
          model: '/works/untitled-co-op/cast/king.glb',
          image: '/works/untitled-co-op/cast/king.webp',
        },
        {
          slug: 'superior-officer',
          name: 'The Superior Officer',
          role: 'Command',
          note: 'Expects to be served first at the drink shop and leaves without paying. On the battlefield, it is a superior’s order Cám refuses.',
          model: '/works/untitled-co-op/cast/superior-officer.glb',
          image: '/works/untitled-co-op/cast/superior-officer.webp',
        },
      ],
    },
    {
      kind: 'gallery',
      id: 'places',
      label: 'Places',
      heading: 'Seven locations, blocked out',
      intro:
        'Built in Blender by Python scripts that share one geometry library — architecture, roofs, market stalls, water, terrain. Every gameplay stop in the chapter documents has a named camera. This is a first pass: procedural materials, simplified figures for scale, no animation, and nothing imported into Unity yet.',
      items: [
        { src: '/works/untitled-co-op/places/01-puppet-square-aerial.webp', caption: 'Puppet Square · Intro', note: 'The theatre, the audience benches and the waterfront, at night.' },
        { src: '/works/untitled-co-op/places/02-puppet-square-street.webp', caption: 'Puppet Square · Arrival street', note: 'The walk in towards the stage.' },
        { src: '/works/untitled-co-op/places/03-provisions-shop.webp', caption: 'Tấm’s village · Provisions shop', note: 'Her first act in Chapter 1: stocking the shelves.' },
        { src: '/works/untitled-co-op/places/04-river-boat.webp', caption: 'Cám’s countryside · The river', note: 'Where he learns the boat Chapter 2 turns into a two-person version.' },
        { src: '/works/untitled-co-op/places/05-terraces-from-top.webp', caption: 'Cám’s countryside · Hillside terraces', note: 'The view from the top of his last climb.' },
        { src: '/works/untitled-co-op/places/06-festival-overview.webp', caption: 'Festival · The whole site', note: 'Eight connected areas from the flower gate to the quiet landing downstream.' },
        { src: '/works/untitled-co-op/places/07-festival-docks.webp', caption: 'Festival · Docks and boat race', note: 'The last act of the escape starts here.' },
        { src: '/works/untitled-co-op/places/08-drink-shop-interior.webp', caption: 'Drink shop · Behind the counter', note: 'The workspace both players share for five days.' },
        { src: '/works/untitled-co-op/places/09-drink-shop-cutaway.webp', caption: 'Drink shop · Cutaway', note: 'Counter, prep area and courtyard seating, with the river behind.' },
        { src: '/works/untitled-co-op/places/10-capital-gate.webp', caption: 'The capital · Gate', note: 'Arrival, at eye level.' },
        { src: '/works/untitled-co-op/places/11-council-hall.webp', caption: 'Two Fronts · Council hall', note: 'Inside the palace, on Tấm’s side of Chapter 5.' },
        { src: '/works/untitled-co-op/places/12-ridge-fort.webp', caption: 'Two Fronts · Ridge fort', note: 'The final defence, on Cám’s side.' },
      ],
    },
    {
      kind: 'prose',
      id: 'premise',
      label: 'The premise',
      heading: 'Two ordinary people, on opposite sides of the same failure.',
      pull: 'Perhaps we are waiting for the wrong people.',
      body: [
        'The opening is a puppet show. Ninety seconds of two scenes running at once — a starving army losing ground outside the border, and officials inside the palace loading the grain they took onto their own carts. Then an arm moves wrong. Wood strikes wood, strings become visible, and both halves fold together into two sides of one stage in front of a crowd.',
        'The puppet master asks that crowd who will save them. The lanterns go out one at a time until two spotlights are left, on two teenagers standing separately among the spectators. They are the two player characters, and the screen splits.',
        'The external threat is an invading army. The internal threat is a leadership that taxes the people defending it and would rather surrender than lose what it owns. The first three chapters are deliberately small — stocking a shop, clearing a path, running from trouble at a festival, working five days in a drink shop — because the last two only land if both players already know what the everyday was worth.',
        'Then they split. One goes to the battlefield. The other goes in through the palace service gate with a job in the kitchens and one sentence to work from: if I can get inside, perhaps I can make someone listen.',
      ],
    },
    {
      kind: 'stages',
      id: 'chapters',
      label: 'Chapters',
      heading: 'Five playable chapters, then the epilogue',
      intro:
        'The structure is agreed. Missions, dialogue and tactics are not. What follows is the shape each chapter has to deliver, and what it is allowed to cost.',
      items: [
        {
          index: '00',
          name: 'The Puppet Show',
          role: 'Locked 60–90 second opening. Not playable.',
          image: '/works/untitled-co-op/chapters/00-puppet-square.webp',
          imageNote: 'Puppet Square — the stage the whole opening folds into. Blender blockout.',
          body: [
            'Two staged views, the puppet reveal, the pullback to the audience, the question, the two spotlights, and the handoff to split-screen play.',
            'Deliberately cheap to prove: the real-to-puppet transformation is the whole trick, and it has to be tested before it is allowed to set a visual standard the rest of the campaign cannot afford.',
          ],
          intent:
            'A ninety-second sequence must not set the art bar for twenty hours of game. Prove the reveal reads, then cap it.',
          teaches: ['Story / cinematic gameplay', 'Set piece'],
        },
        {
          index: '01',
          name: 'Two Worlds',
          role: 'Separate everyday journeys. Each player is going to find their mother.',
          image: '/works/untitled-co-op/chapters/01-tam-village.webp',
          imageNote: 'Tấm’s village from the harbour. Cám’s countryside — logging clearing, river, farm and hillside terraces — is its own scene.',
          body: [
            'Four acts each, run in parallel. She stocks the shop, crosses the neighbourhood, cooks a short sequence of dishes, and makes a market delivery. He clears felled timber, learns the boat, recovers loose animals, and crosses the hillside.',
            'Neither of them is going to a festival yet — they do not know each other. The invitations arrive in the closing cinematics, which is the first thing that points the two halves at one another.',
          ],
          intent:
            'The acceptance test here is timing, not content: if one route runs long, the other player spends a large part of the chapter waiting. The boat built here is the same boat Chapter 2 turns into a two-person version.',
          teaches: ['Exploration', 'Simulation / daily life', 'Traversal', 'Vehicle / mount'],
        },
        {
          index: '02',
          name: 'The Festival',
          role: 'They meet. Five cooperative acts, one continuous escape.',
          image: '/works/untitled-co-op/chapters/02-festival.webp',
          imageNote: 'The procession field — drums, the dragon dance, and the crowd the two of them blend into under a costume.',
          body: [
            'A group harasses her, he steps in, and they are immediately outnumbered. The escape is the chapter: a market chase, a stealth section, a stretch spent operating opposite ends of the same dragon costume, a rooftop climb, and a boat paddled out to safety.',
            'It ends quietly — a kiss on the cheek, and they go separate ways.',
          ],
          intent:
            'Every one of the five acts has to need both players, and the transitions have to read as one escape rather than five minigames. His intervention is staged tightly on purpose: it does not justify building a combat system two chapters before combat exists.',
          teaches: ['Chase / escape', 'Stealth', 'Cooperative mechanics', 'Traversal', 'Relationship / trust'],
        },
        {
          index: '03',
          name: 'The Drink Shop',
          role: 'Five working days. The war arrives through the customers.',
          image: '/works/untitled-co-op/chapters/03-drink-shop.webp',
          imageNote: 'The drink shop from the shared courtyard, beside the restaurant.',
          body: [
            'One loop — read the order, collect, prepare, hand off, serve, reset — escalated across five days. Day one is forgiving. Day two brings wounded soldiers. Day three is the superior officer who is served and leaves without paying, with the day’s earnings making the loss visible. Day four is the busiest full service, with both kinds of customer in the room at once.',
            'Day five starts normally, then the advance reaches them. Civilians arrive, service ends early, and the shop closes so the group can move toward the capital.',
          ],
          intent:
            'Rising prices and taxes are authored story pressure, not an economy simulation. The invasion has to interrupt the routine as an interruption — not as one more score challenge with a harder target.',
          teaches: ['Resource management', 'Cooperative mechanics', 'Economy', 'Social / dialogue'],
        },
        {
          index: '04',
          name: 'The Recruitment',
          role: 'The king speaks. Afterwards they prepare for different things.',
          image: '/works/untitled-co-op/chapters/04-capital.webp',
          imageNote: 'The palace courtyard, set for the king’s speech.',
          body: [
            'The journey to the capital is cinematic. They enter the palace together and hear the king promise protection — the last thing they do side by side for a while.',
            'He trains: movement and defence, attacking and reading enemy signals, working beside a crew, then a short combined exercise. She talks to people — hears a concrete problem, asks follow-ups, sees the circumstances, and recognises the pattern of help that was promised and never arrived.',
          ],
          intent:
            'Every training exercise has to teach something Chapter 5 actually uses; anything else gets cut. Her side needs conversational agency without becoming a detective system — a compact journal of what she has learned is enough. She is not employed by the palace yet.',
          teaches: ['Combat training', 'Investigation', 'Social / dialogue', 'Character progression'],
        },
        {
          index: '05',
          name: 'Two Fronts',
          role: 'The final playable chapter. Two genres, one conflict.',
          image: '/works/untitled-co-op/chapters/05-two-fronts.webp',
          imageNote: 'Both fronts in one scene — the palace and town on the left, the battlefield across the river.',
          body: [
            'His half is direct battlefield action: a first manageable encounter with his crew, an escalation that demonstrates what bad orders and thin supplies cost, and a final battle where he is given a concrete order, understands why obeying it abandons the people, and pursues a different objective instead. He wins.',
            'Her half is a decision-driven palace drama and she never fights. Kitchen entry, earning trust and access, measuring the palace’s promises against what she saw at the shop, discovering the surrender, and getting the abandoned people out. Every consequential decision has exactly one correct answer; every other answer is a short failure and a local retry, not an alternate ending. She succeeds, and loses her position and her protection for it.',
            'They reunite inside this chapter, with his crew and the people she saved, and start planning to take the palace back.',
          ],
          intent:
            'Synchronisation is the hard part: finished encounters have to resolve into a safe state, shared revelations only fire at safe boundaries, and neither player replays completed work because the other one failed. If one role routinely finishes far earlier, the fix is pacing — not filler.',
          teaches: ['Combat', 'Choice & consequence', 'Asymmetric gameplay', 'Investigation'],
        },
        {
          index: '06',
          name: 'Cinematic Epilogue',
          role: 'Closing sequence. Not another set of missions.',
          body: [
            'Support gathers, the fight back happens, the palace is reclaimed and the enemy driven out. He leads the military effort; she brings people together and stays non-combat.',
            'It closes on ordinary life resuming — families going home, markets reopening, the drink shop serving again. Whether it returns to the puppet storyteller is still open.',
          ],
          intent:
            'Reuse familiar places and faces so restoration means something. No new playable missions and no retry sequences: the audience should be able to trace the wider victory back to what the two of them earned on screen.',
          teaches: ['Story / cinematic gameplay'],
        },
      ],
    },
    {
      kind: 'systems',
      id: 'systems',
      label: 'Systems',
      heading: 'What has to exist before any of that is playable',
      intro:
        'The chapters above are content. These are the foundations they all sit on — and the reason the overall figure is still in single digits despite everything above.',
      items: [
        {
          code: 'S1',
          name: 'Two-player session, split-screen and online',
          body: 'Local split-screen and online co-op are both intended capabilities, with separate objectives and cameras per player. Their practical design has to be proven early, not discovered in Chapter 5.',
          build: 'Unproven. The highest-risk item in the plan; Phase 2 exists to answer it.',
          state: 'planned',
        },
        {
          code: 'S2',
          name: 'Checkpoints and independent recovery',
          body: 'Each player fails and retries on their own clock. One player’s failure must not reset the other’s progress, and a faster player must never be parked in unwinnable combat while the other retries a decision scene.',
          build: 'Specified as per-act local checkpoints with tested entry and exit states. Not implemented.',
          state: 'planned',
        },
        {
          code: 'S3',
          name: 'Interaction, traversal and the boat',
          body: 'One shared vocabulary of carrying, placing, climbing, swinging and steering, reused from the first shop shift to the final escape. Depth comes from layout and escalating constraint, not from new verbs per chapter.',
          build: 'Grey-box only.',
          state: 'planned',
        },
        {
          code: 'S4',
          name: 'Combat — one style, few behaviours',
          body: 'Starts with a single coherent weapon style and a small set of distinct opponent behaviours, expanded only if the prototype proves the need. One of the two leads never fights at all, which halves the surface.',
          build: 'Not started. References are noted in the design documents; no system chosen.',
          state: 'planned',
        },
        {
          code: 'S5',
          name: 'Dialogue and authored decision scenes',
          body: 'The palace half needs decisions with authored prior information, one correct answer, a stated reason each wrong answer fails, a short failure scene and a precise local checkpoint. Access is gated by authored trust milestones rather than a relationship simulation.',
          build: 'Not started. The shape is specified in the plan; no scenes are written.',
          state: 'planned',
        },
        {
          code: 'S6',
          name: 'Grey-box prototype scenes',
          body: 'Three throwaway scenes standing in for the shop, the festival coordination and the two-fronts split, built headless so they can be smoke-checked without a GPU.',
          build: 'Unity 6000.2.9f1, null graphics device. Shop, festival and two-fronts all report ready and pass the self-check.',
          state: 'building',
        },
      ],
    },
    {
      kind: 'roadmap',
      id: 'roadmap',
      label: 'Roadmap',
      heading: 'Where the line is drawn',
      intro:
        'The last column is the important one. Two-player co-op does not imply any of it, and each item there would be its own production.',
      columns: [
        {
          state: 'built',
          items: [
            'Intro script, 90 seconds, shot by shot',
            'Six chapter documents',
            'Agreed creative boundaries',
            'Eleven-phase production plan with gate criteria',
            'Storyboards, intro to Chapter 5',
            'Environment blockouts, all seven locations',
            'Main cast modelled — leads, families, court',
          ],
        },
        {
          state: 'building',
          items: ['Grey-box prototype scenes', 'Headless build and smoke-check pipeline'],
        },
        {
          state: 'planned',
          items: [
            'Split-screen and online co-op proof',
            'Checkpoint and recovery model',
            'Shared traversal and interaction vocabulary',
            'One combat style, few opponent behaviours',
            'Authored decision scenes for the palace',
            'Cast and environments into Unity — rigging check, Mixamo retargeting',
            'Five chapters of playable acts',
            'Cinematics, audio and accessibility passes',
          ],
        },
        {
          state: 'excluded',
          items: [
            'Solo play and AI companions',
            'Console versions and cross-play',
            'Host migration',
            'A persistent business-management economy',
            'A free-market price simulation',
            'General tree-physics simulation',
            'Independently simulated crowds',
            'A playable palace-retaking chapter',
          ],
        },
      ],
    },
    {
      kind: 'table',
      id: 'shape',
      label: 'Shape',
      heading: 'What it is, and what is still open',
      rows: [
        ['Genre', 'Co-op story adventure · two players · third-person'],
        ['Players', 'Two, required. Local split-screen and online both intended'],
        ['Structure', 'Five playable chapters, then a non-playable cinematic epilogue'],
        ['Asymmetry', 'One lead fights. The other never does, and plays a decision-driven palace drama'],
        ['Engine', 'Unity 6 proposed, on existing experience. Rendering and asset workflow unvalidated'],
        ['Title', 'Undecided. The leads carry the working names from the design documents'],
        ['Setting', 'Vietnamese cultural imagery. Kingdom, period and relationship to real history all open'],
        ['Enemy', 'An invading army. The specific historical or fictional framing is not settled'],
        ['State', 'Story, storyboards, environment blockouts and main cast exist. Nothing is playable yet'],
      ],
    },
    {
      kind: 'log',
      id: 'log',
      label: 'Log',
      heading: 'Since it started',
      entries: [
        {
          date: '20 Sep 2026',
          title: 'Story documents closed out',
          body: 'The intro script and all six chapter documents finished, and the gameplay category library filed as an idea bank rather than a feature checklist — it still refers to an older version of the story and does not override the current chapters.',
          tags: ['story'],
        },
        {
          date: '20 Sep 2026',
          title: 'Production Master Plan v1',
          body: 'Eleven phases, a scope model, per-chapter work packages, acceptance criteria, risks and the first ten working sessions. It states plainly that the documents are a foundation and not a technical specification, and that co-op has to be proven before anything is built on top of it.',
          tags: ['planning'],
        },
        {
          date: '21 Sep 2026',
          title: 'First prototype scenes build clean',
          body: 'Shop, festival and two-fronts grey-box scenes building headless under Unity 6000.2.9f1 and passing their smoke checks. A shader null in the shop scene’s box colouring was the last thing in the way.',
          tags: ['unity', 'prototype'],
        },
        {
          date: '24 Sep 2026',
          title: 'Storyboards, intro to Chapter 5',
          body: 'About 120 split-screen frames — the puppet show, both Chapter 1 routes, the festival escape, all five days at the drink shop, the capital and the two fronts through to the reunion. The epilogue is not boarded yet.',
          tags: ['story', 'storyboard'],
        },
        {
          date: '25 Sep 2026',
          title: 'Cast references and models',
          body: 'Reference sheets for the leads at two ages, their mothers, the court, the officers, the enemy and the chapter NPCs, then 27 models built from them in Tripo at around ten thousand triangles each. Seven of the eight shown above came with an automatic rig. None are in Unity yet.',
          tags: ['characters'],
        },
        {
          date: '28 Sep 2026',
          title: 'Environment V1 — seven locations',
          body: 'Every location blocked out in Blender from Python build scripts, with a camera on each gameplay stop and a top-down route map per chapter. Each storyboard frame was then rebuilt as a camera in the matching scene, so the boards and the blockouts can be compared shot for shot.',
          tags: ['environment', 'blender'],
        },
        {
          date: '28 Sep 2026',
          title: 'Animation library and sound list',
          body: 'Around 130 Mixamo motions gathered for climbing, carrying, cooking, combat and reactions, and a per-chapter sound-effect list written. Neither is hooked up to anything yet.',
          tags: ['animation', 'audio'],
        },
      ],
    },
  ],
};
